### ISSUE TITLE
Script Error found in ODC version of Outsystems 

### ISSUE THREAD

**Issue by polauuuuu** [OutSystems/UltimatePDF-ExternalLogic#1]
Hello, I am an Outsystems ODC User. I tried following the document of PDF Forge of UltimatePDF with the instructions of following link https://github.com/OutSystems/UltimatePDF-ExternalLogic, but it seems there is a script error as attached when I added the system event 
![image](https://github.com/OutSystems/UltimatePDF-ExternalLogic/assets/117147913/d3a4efe8-38e8-4f6c-aea0-a0921378a818)
![image](https://github.com/OutSystems/UltimatePDF-ExternalLogic/assets/117147913/51a487d1-b1b3-4c7c-9e1c-e619ac5b1797)

By checking consoles 
![image](https://github.com/OutSystems/UltimatePDF-ExternalLogic/assets/117147913/a6d453c6-639d-407e-a350-46363925d16a)
several scripts are missing. May I seek assistance to upgrade those at Forge to the ODC version? Thanks a lot for your support.

**Comment by diogopaulo** [comment]
Recent changes to the application runtime broke the Screen to PDF functionality. We have removed that feature in the newer version of the plugin. At the moment we are trying to understand how we can reimplement this use case with the new runtime code.

**Comment by diogopaulo** [comment]
Screen To PDF feature and preview argument are fixed in the version 1.1.9 of the UltimatePDF library.
