### ISSUE TITLE
Preview parameter

### ISSUE THREAD

**Issue by rpoels** [OutSystems/UltimatePDF-ExternalLogic#3]
Hello,

I am using the UltimatePDF component in ODC, but it seems that the _preview_ parameter in the ScreenToPDF_OnInitialize client action is incorrectly implemented as output parameter where it should be an input parameter.
Hope this can be fixed.

![image](https://github.com/OutSystems/UltimatePDF-ExternalLogic/assets/98035978/d31da0ef-21d3-44fd-8f40-226a2ea750ec)

**Comment by diogopaulo** [comment]
Recent changes to the application runtime broke the Screen to PDF functionality. We have removed that feature in the newer version of the plugin. At the moment we are trying to understand how we can reimplement this use case with the new runtime code.

**Comment by diogopaulo** [comment]
Screen To PDF feature and preview argument are fixed in the version 1.1.9 of the UltimatePDF library
